### ISSUE TITLE
Horizontal slide

### ISSUE THREAD

**Issue by Emanuele20** [alleyinteractive/revealjs-wp-theme#8]
Maybe is a stupid question... plugin works great but...i can only add a vertical slide, how can i create horizontal? And about fragments? How can i set this? Really thx! Bye!

**Comment by mboynes** [comment]
Hi @Emanuele20, each post in the slides post type is a horizontal slide and you order them using the "Order" field.

Fragments require you to write a little HTML, you add the class "fragment" to the element you want to be a fragment. See https://github.com/hakimel/reveal.js/ for more info on that.

**Comment by Emanuele20** [comment]
...sorry...ve a look...
![02](https://cloud.githubusercontent.com/assets/19958514/16118774/e529f408-33d8-11e6-9985-658c7e901e81.png)
![03](https://cloud.githubusercontent.com/assets/19958514/16119007/d3afdfca-33d9-11e6-8679-eb5bf4c7b0eb.png)

**Comment by mboynes** [comment]
All "slide" posts are horizontal slides. In the left navigation, clicking "Add New Slide" will add a new horizontal slide. From within each horizontal slide, you can add vertical slides.

**Comment by Emanuele20** [comment]
So if I understood well from within each horizontal slide, you can add vertical slides **but is not possible add new horizontal slides** it mean that in front-end i can use my arrow up-down and no left-right...

**Comment by mboynes** [comment]
No. If you create 3 slide posts, then go to the site homepage, you navigate between them using the left-right arrows. Think of it as a parent child relationship, horizontal slides are the parent, and vertical slides are its children.

Everything you want to do is possible here, just go play around with it.
